name: Deploy Azure Resources using Bicep

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # AZURE_CREDENTIALS is stored in GitHub Secrets

    - name: Set up Bicep
      run: |
        # Install the latest Azure CLI
        az upgrade --yes
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        # Install Bicep CLI
        az bicep install

    - name: Deploy Bicep Template
      run: |
        # Ensure Azure CLI is up to date
        az upgrade --yes
        # Deploy the Bicep template
        az deployment group create \
          --resource-group "example-rg" \
          --template-file "\infrastructure\main.bicep" \
          --parameters "\infrastructure\param.json"

