name: Deploy Azure Resources using Bicep

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # AZURE_CREDENTIALS is stored in GitHub Secrets

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Azure CLI Action
      uses: azure/setup-cli@v3

    - name: Verify Azure CLI installation
      run: az --version

    - name: Deploy Bicep Template
      run: |
        # Ensure Azure CLI is up to date
        az upgrade --yes
        # Deploy the Bicep template
        az deployment group create \
          --resource-group "example-rg" \
          --template-file "\infrastructure\main.bicep" \
          --parameters "\infrastructure\param.json"

